### PR TITLE
Add Feature: Console Log Window

### LINKED ISSUE #439: Add a "console" window that displays all output, for easier troubleshooting
We get a lot of issues like:

- I hit "START STREAMING" and nothing happens
- The GUI freezes on startup
- etc.

Sure, it would be great to have more robust feedback to the user when something fails.

But in the meantime, it would be helpful to have a way for users to look at the program's console output.

### PR DESCRIPTION
**Pull request by retiutut**
Fixes #439
- [x] Implement front-end solution (Cog Button in GUI top right)
- [x] Implement consoleLogTest.pde with at-scale solution
- [x] Test scrolling functionality
- [x] Discuss when consoleWindow should be redrawn so it doesn't impact overall GUI performance. 
*Update occurs based on user interaction and consolePrint()s only* 😎 
_____
- [x] Console window appears behind the gui. Should appear in front. https://github.com/OpenBCI/OpenBCI_GUI/pull/448/commits/ff4dcb059556ec4f89df1263e897d12f2673304e
- [x] Pressing the button multiple times opens multiple console windows. https://github.com/OpenBCI/OpenBCI_GUI/pull/448/commits/aae8541f08756e2d6cf3f769fa8e290ccde415cb
- [x] consoleWindow multiline string support https://github.com/OpenBCI/OpenBCI_GUI/pull/448/commits/ff4dcb059556ec4f89df1263e897d12f2673304e
- [x] Text is not selectable, copyable. (Not possible)
- [x] Copy text with keypress 'c' or 'C' https://github.com/OpenBCI/OpenBCI_GUI/pull/448/commits/61469f6408adf8f1c978de181a1b996a2614b486
- [x] Text is not scrollable with the mouse wheel. https://github.com/OpenBCI/OpenBCI_GUI/pull/448/commits/54fc9ec0bb2e6e66ea0796a765a0bab8152642e9
- [x] Resizing/maximizing the gui make the cog button go away. Sometimes it makes the other buttons go away. https://github.com/OpenBCI/OpenBCI_GUI/pull/448/commits/41ece8158bfb3e5d347d48d908a99e1f1bfd9beb
- [x] **Java exceptions don't print out in the console log.** Also, what about error output printed by libraries we import?https://github.com/OpenBCI/OpenBCI_GUI/pull/448/commits/41ece8158bfb3e5d347d48d908a99e1f1bfd9beb
_____
- [x] change console window icon https://github.com/OpenBCI/OpenBCI_GUI/pull/448/commits/10bf2b5445a50b3795e10ad245b436731a575281
- [x] Move console-data.txt to the `SavedData` directory https://github.com/OpenBCI/OpenBCI_GUI/pull/448/commits/f50fdd07235fbd77812d54eb4bfb2460f1af8a89
- [x] Account for long console messages (example: comPorts) https://github.com/OpenBCI/OpenBCI_GUI/pull/448/commits/a51ccc29a81f1f1a6f6e13e759806501d8fe63fa
- [x] Convert consoleWindow to ContolP5 Textarea with auto scrollbars https://github.com/OpenBCI/OpenBCI_GUI/pull/448/commits/a51ccc29a81f1f1a6f6e13e759806501d8fe63fa
- [x] Remove ScrollRect from GUI implementation of consoleWindow https://github.com/OpenBCI/OpenBCI_GUI/pull/448/commits/a51ccc29a81f1f1a6f6e13e759806501d8fe63fa
- [x] Add button to copy full text https://github.com/OpenBCI/OpenBCI_GUI/pull/448/commits/a9a82eff3f8c4ae7d5de09ef51e98d3bfcddc624
- [x] Add button to copy last line
https://github.com/OpenBCI/OpenBCI_GUI/pull/448/commits/a9a82eff3f8c4ae7d5de09ef51e98d3bfcddc624
- [x] Add button to open console log file using default text editor
https://github.com/OpenBCI/OpenBCI_GUI/pull/448/commits/a9a82eff3f8c4ae7d5de09ef51e98d3bfcddc624
- [x] Fine tune console log display window
- [x] Complete initial testing
_____
- [x] Pass code review and testing
- [ ] Update version/info in changelog, info.plist.tmpl, and openbci_gui.pde

### CODE REVIEW

**Comment by daniellasry** [comment]
Just tried this. Look cool! I noticed these issues:

1. Console window appears behind the gui. Should appear in front.
2. Pressing the button multiple times opens multiple console windows.
3. Text is not selectable, copyable.
4. Text is not scrollable with the mouse wheel.
5. Resizing/maximizing the gui make the cog button go away. Sometimes it makes the other buttons go away.
6. **Java exceptions don't print out in the console log.**

**Comment by retiutut** [comment]
Screen Shot 2019-03-08 at 4 36 27 PM

**Comment by retiutut** [comment]
Screen Shot 2019-03-08 at 4 53 31 PM

**Comment by daniellasry** [comment]
Confirmed working in standalone. Merging.

**Pull request merged**
