### PR TITLE
Update to Processing 4 beta 3 CI pipeline

### LINKED ISSUE #674: RadioConfig Buttons Crash GUI w/ Processing 4
## Problem

The GUI crashes and a log file is saved in the application directory on Windows.

## Expected 

RadioConfig buttons for Manual Cyton Config need to work on Windows, without the GUI crashing.

## Operating System and Version
Windows

## GUI Version

4.2.0

## Running standalone app

Happens in Standalone and Processing-Java on Windows only

## Type of OpenBCI Board

Cyton and Cyton+Daisy

## Are you using a WiFi Shield?
No

## Console Log
```
Console Log Started at Local Time: 2020-01-31_18-48-18
Screen Resolution: 1920 X 1080
Welcome to the Processing-based OpenBCI GUI!
For more information, please visit: https://openbci.github.io/Documentation/docs/06Software/01-OpenBCISoftware/GUIDocs
Launching application from local data dir
OpenBCI_GUI: hubStart: OS Detected: Windows
TopNav: Internet Connection Successful
Local Version: 420, Latest Version: 420
GUI is up to date!
OpenBCI_GUI::Setup: Sample Data exists in Documents folder.
ControlP5 2.2.6 infos, comments, questions at http://www.sojamo.de/libraries/controlP5
CP: Playback History Size = 1
OpenBCI_GUI::Setup: Setup is complete!
Instantiating hub object...
Hub: CheckHubInit: The GUI is connected to the Hub!
sourceList: click! 
setInterface: curInterface: -1
channel count set to 8
Setting Latency to 10000
Setting WiFi Internet Protocol to udpBurst
Setting WiFi style to dynamic
[DEFAULT]: Protocol Serial Selected for Cyton
setInterface: curInterface: 0
Setting sample rate for Cyton to 250Hz


sample rate set to: 250
[DEFAULT]: Transfer Protocol set to serial
serialList: click! 
[DEFAULT]: OpenBCI Port Name = COM4
Radios_Config: scan_channels
[DEFAULT]: Attempting to open Serial/COM port: COM4
Radios_Config: connect_to_portName: Attempting to open serial port: COM4
```
[hs_err_pid15512.log](https://github.com/OpenBCI/OpenBCI_GUI/files/4141971/hs_err_pid15512.log)

### LINKED ISSUE #1025: The type Serial is ambiguous.
## Problem

Issue starting the OpenBCI GUI with the latest version of Processing v4.0b3. When pressing "start," the following error occurs. **I resolved the issue by downgrading Processing to v3.5.4, but wanted to make sure ya'll were aware of the issue.**

## Expected 

Should start the OpenBCI GUI on pressing start.

## Operating System and Version

Windows 10

## GUI Version

v5.0.9

## Running standalone app

Running on Processing 4.0b3

## Console Log

image

### PR DESCRIPTION
**Pull request by retiutut**
The purpose of this PR is to update the entire GUI to use Processing 4 and OpenJDK 11 (aka Java 11). Processing 4 is now in the beta stage and is much more stable than it was a year ago. I have been testing this periodically since the first Processing 4 release, and it seems it is finally time to make this change for the GUI.

- [x] Fixes #674 

- [x] Update BrainFlow jar to one that uses Java 11

- [x] Fixes #1025 

- [x] Test all BrainFlow boards in the GUI using updated BrainFlow jar

### CODE REVIEW

**Comment by retiutut** [comment]
@Andrey1994 Can you upload the latest BrainFlow jar that supports all 3 OS and Java 11?

**Comment by Andrey1994** [comment]
link to the latest jar to try https://github.com/brainflow-dev/brainflow/releases/download/4.8.2/brainflow-jar-with-dependencies.jar

**Comment by retiutut** [comment]
https://github.com/OpenBCI/OpenBCI_GUI/issues/1025

**Comment by retiutut** [comment]
@Andrey1994 I have tested each board, playback mode, synthetic mode, and the base processing.serial.Serial class for Cyton dongle coms.

I did not test the WiFi shield as it is discontinued at this time and probably works also.

**Review by Andrey1994 — APPROVED** [review]

**Pull request merged**
