### PR TITLE
sync gang disc threads

### PR DESCRIPTION
**Pull request by Andrey1994**
Signed-off-by: Andrey Parfenov <a1994ndrey@gmail.com>

### CODE REVIEW

**Comment by daniellasry** [comment]
1. If a user clicks the button twice, would it make more sense to halt the old thread in favor of the new one? I can image someone plugging in the dongle then pressing the button. It won't work until the previous thread is done. (and what if the old thread is stuck waiting for a timeout or something?)
1. Should we do the same thing for wifi refresh button and cyton port refresh button?

**Comment by retiutut** [comment]
Does this potentially fix issue found in #805 ?

```
ControlPanel: Found BLED112 Dongle on COM port: COM3
openbci_gui_helpers.GanglionError: Error in scan for ganglions:PORT_OPEN_ERROR
	at openbci_gui_helpers.GUIHelper.scan_for_ganglions(GUIHelper.java:69)
	at OpenBCI_GUI$BLEBox$1.run(OpenBCI_GUI.java:5502)
```

**Comment by Andrey1994** [comment]
1. Here it will not even create a new thread if previous is running. I think race condition between setting bleRefreshRunning in practice will not happen
2. We can and it will not hurt but not sure that its necessary

**Comment by Andrey1994** [comment]
> ControlPanel: Found BLED112 Dongle on COM port: COM3
> openbci_gui_helpers.GanglionError: Error in scan for ganglions:PORT_OPEN_ERROR
> 	at openbci_gui_helpers.GUIHelper.scan_for_ganglions(GUIHelper.java:69)
> 	at OpenBCI_GUI$BLEBox$1.run(OpenBCI_GUI.java:5502)

depends on what you mean by this issue....
more likely you will not see these messages

**Pull request merged**
