### PR TITLE
brainflow 3.2.0

### PR DESCRIPTION
**Pull request by Andrey1994**
Signed-off-by: Andrey Parfenov <a1994ndrey@gmail.com>

There are a lot of changes across all boards, I tested it but lets double check

### CODE REVIEW

**Comment by retiutut** [comment]
Do we just need to test if all boards can connect? Anything specific to look for?

**Comment by Andrey1994** [comment]
changes were mostly about wifi shield, lets confirm it on different OSes

**Comment by daniellasry** [comment]
@Andrey1994 do you need to update the jar with the recent 65536 *4 change for windows?

**Comment by Andrey1994** [comment]
I think 65536 *2 should work exactly the same(but not sure), so we can skip it for now

**Comment by daniellasry** [comment]
I'm having an issue since meging this jar:

```
[2020-07-20 13:53:48.943] [brainflow_logger] [debug] use stub streamer
Brainflow start streaming

[2020-07-20 13:53:48.944] [brainflow_logger] [trace] recieved 0 bytes

[2020-07-20 13:53:51.054] [brainflow_logger] [trace] recieved 204 bytes

[2020-07-20 13:53:51.064] [brainflow_logger] [trace] response data OK

HTTP/1.0 502 Bad Gateway

Content-Type: text/plain

Access-Control-Allow-Origin: *

Content-Length: 75

Connection: close



Error: timeout getting command response, be sure board is fully connected



[2020-07-20 13:53:54.065] [brainflow_logger] [warning] WSAGetLastError is 10060

[2020-07-20 13:53:57.065] [brainflow_logger] [warning] WSAGetLastError is 10060

[2020-07-20 13:54:00.065] [brainflow_logger] [warning] WSAGetLastError is 10060

[2020-07-20 13:54:03.066] [brainflow_logger] [warning] WSAGetLastError is 10060

[2020-07-20 13:54:06.066] [brainflow_logger] [warning] WSAGetLastError is 10060
```

no data is streaming

**Comment by Andrey1994** [comment]
```
Error: timeout getting command response, be sure board is fully connected
```
it looks like board issue

**Comment by daniellasry** [comment]
Works fine with the old jar

**Comment by Andrey1994** [comment]
is it stable? Can it be a random failure of device?

**Comment by daniellasry** [comment]
Nevermind, it was a random failure. I went back to new jar and now it works fine 😕

**Comment by daniellasry** [comment]
Good news: I'm not seeing the packet loss after your change so far! gonna let it run for a while

**Comment by Andrey1994** [comment]
> Good news: I'm not seeing the packet loss after your change so far! gonna let it run for a while

if you see, lets also try * 4

**Comment by daniellasry** [comment]
8 minutes so far, and it only happened once: 

WARNING: Lost 144 Samples Between 236-125

**Comment by daniellasry** [comment]
It just happened 4 times in a row, so I'm gonna try * 4

**Comment by Andrey1994** [comment]
where does 144 come from? its 4752 bytes this value makes no sense for me.....
We can try to recv multiple packages in a single call instead only one. I dont understand how it can help but can try

**Comment by daniellasry** [comment]
I think there is an improvement with *4. In 14 minutes i only had these losses:

WARNING: Lost 144 Samples Between 53-198
WARNING: Lost 208 Samples Between 205-158
WARNING: Lost 88 Samples Between 174-7

**Comment by daniellasry** [comment]
i don't know why it's almost always 144

**Comment by Andrey1994** [comment]
Ok, I wil create new release with * 4. Or do you wanna try even bigger values?

**Comment by daniellasry** [comment]
I'm gonna try some even bigger values, to see if i can make completely go away. 

The % loss is very small as it is though

**Comment by daniellasry** [comment]
I see no improvement even when going to *8, so there's no reason to increase it from *4

**Comment by daniellasry** [comment]
Actually, I went back to old brainflow jar without moving the board from its location, and it's the same. It's not worse. I see the brainflow warning messages but the packet loss is not worse.

I bet it's an issue with the firmware...

**Pull request merged**
