### PR TITLE
Cleanly stop streaming and close board on quit

### PR DESCRIPTION
**Pull request by daniellasry**
Simply call haltSystem() on quit.

### CODE REVIEW

**Comment by Andrey1994** [comment]
What is haltSystem? I dont see definition in code and at processing.org

**Comment by daniellasry** [comment]
It's defined in OpenBCI_GUI.pde

**Comment by daniellasry** [comment]
It's the function that gets called when you stop a session

**Comment by daniellasry** [comment]
offline discussion: andrey pointed out that brainflow should already be stopping the stream when the board object is destructed. It seems like it does.

Still, i think this change might be for the best, since it covers things like closing the SD card, closing the log file on exit... It will avoid more problems like that in the future.

**Pull request merged**
