### PR TITLE
update brainflow jar

### PR DESCRIPTION
**Pull request by Andrey1994**
Signed-off-by: Andrey Parfenov <a1994ndrey@gmail.com>

### CODE REVIEW

**Comment by retiutut** [comment]
@Andrey1994 I think the BrainFlow library was deleted instead of updated.

**Comment by Andrey1994** [comment]
https://github.com/OpenBCI/OpenBCI_GUI/blob/brianflow_new_ver/OpenBCI_GUI/libraries/brainflow/library/brainflow.jar here is this file

**Comment by retiutut** [comment]
@Andrey1994 I can see on Github Desktop that the file was modified, but for some reason Github in browser shows this:

Screen Shot 2021-02-08 at 1 35 08 PM

It's fine and the file was indeed updated.

_______

@Andrey1994 Do you think any other channels would be added to BrainFlow in the next year or two? What happens to this code/PR if another channel is added later?

**Comment by Andrey1994** [comment]
I dont think that smth else will be added to all boards

**Comment by retiutut** [comment]
@Andrey1994 Last questions:

- To confirm, this code and BrainFlow update avoids a breaking change?
- We are clear now to utilize this new BrainFlow feature in a GUI widget/feature? Maybe after restoring Focus widget?

**Pull request merged**
