### PR TITLE
Hot Fix NullPointer error related to missing folder and GUI-wide settings file

### LINKED ISSUE #1003: OpenBCI GUI v5.07 won't start in windows 10
## Problem

The release v5.07 from the 29 of September closes immediatly. OpenBCI_GUI.exe will open for half a second, showing a blank window, and then close immediately.

## Expected 

I xpected the GUI interface to load up for connection of my device

## Operating System and Version

Window 10 pro 64-bi version 20H2

## GUI Version

v5.07

## Running standalone app

Stand alone app

## Type of OpenBCI Board

Cyton

## Are you using a WiFi Shield?

No

## Console Log

Paste any relevant text from the console window here

### PR DESCRIPTION
**Pull request by retiutut**
Fixes #1003 #1004

### CODE REVIEW

**Comment by retiutut** [comment]
@0rang3-blu3

To test the hot fix, Can you please try the following:
- Delete the /Documents/OpenBCI_GUI/Settings folder or make sure it doesn't exist
- Checkout the `development` branch of the GUI (easily done using Github desktop or terminal)
- Run the GUI from Processing or VSCode
- Share Console Log here

Thanks in advance!

**Comment by wrstscrnnm6** [comment]
Seems to launch fine in the Processing IDE.

**Comment by 0rang3-blu3** [comment]
> @0rang3-blu3 @LopezValdes @wrstscrnnm6
> 
> To test the hot fix, Can one or more you please try the following:
> 
> * Delete the /Documents/OpenBCI_GUI/Settings folder or make sure it doesn't exist
> * Checkout the `development` branch of the GUI (easily done using Github desktop or terminal)
> * Run the GUI from Processing or VSCode
> * Share Console Log here
> 
> Thanks in advance!

@retiutut I apologize for my naivety (I'm new to this), I don't see a `settings` folder in the Open_BCI folder – I assume this is ok. Looks like it was missing initially.

I'm not sure what to do with this step though:  
`Checkout the development branch of the GUI (easily done using Github desktop or terminal)
`

**Comment by retiutut** [comment]
> > @0rang3-blu3 @LopezValdes @wrstscrnnm6
> > To test the hot fix, Can one or more you please try the following:
> > 
> > * Delete the /Documents/OpenBCI_GUI/Settings folder or make sure it doesn't exist
> > * Checkout the `development` branch of the GUI (easily done using Github desktop or terminal)
> > * Run the GUI from Processing or VSCode
> > * Share Console Log here
> > 
> > Thanks in advance!
> 
> @retiutut I apologize for my naivety (I'm new to this), I don't see a `settings` folder in the Open_BCI folder – I assume this is ok. Looks like it was missing initially.
> 
> I'm not sure what to do with this step though: `Checkout the development branch of the GUI (easily done using Github desktop or terminal)`

https://desktop.github.com

**Comment by retiutut** [comment]
@0rang3-blu3 Here you go! Happy to share info on how to work with Github. 😃 

Screen Shot 2021-10-01 at 4 55 13 PM

**Comment by 0rang3-blu3** [comment]
Thanks, @retiutut! This is very helpful. I was mostly confused with what to do with the code/how to incorporate it to fix the bug.

**Comment by retiutut** [comment]
> Thanks, @retiutut! This is very helpful. I was mostly confused with what to do with the code/how to incorporate it to fix the bug.

Give it a go and share the Console Log Info from Processing IDE! I'm confident the fix works, but let's test it before rolling it out for everyone. 😃

**Comment by 0rang3-blu3** [comment]
Worked for me too. Thanks, @retiutut! Here's the Console Log info from Processing IDE:

Console Log Started at Local Time: 2021-10-01_15-30-43
Screen Resolution: 1680 X 1050
High-DPI Screen Detected: true
Operating System: Mac
Welcome to the Processing-based OpenBCI GUI!
For more information, please visit: https://docs.openbci.com/Software/OpenBCISoftware/GUIDocs/
OpenBCI_GUI::Setup: Copying sample data to Documents/OpenBCI_GUI/Sample_Data
OpenBCI_GUI::Setup: Created \Documents\OpenBCI_GUI\Recordings\
OpenBCI_GUI::Settings: Creating new GUI-wide Settings file.
OpenBCI_GUI::Settings: Successfully saved GUI-wide settings to file!
ControlP5 2.3.1 infos, comments, questions at http://www.sojamo.de/libraries/controlP5
TopNav: Internet Connection Successful
Local Version: v5.0.7, Latest Version: v5.0.7
GUI is up to date!
OpenBCI_GUI: AuditoryFeedback: Loading Audio...
OpenBCI_GUI: AuditoryFeedback: Done Loading Audio!
OpenBCI_GUI::Control Panel: Playback history file not found.
OpenBCI_GUI::Setup: Setup is complete!
__MOVE__ 310 141
__MOVE__ 245 183
__MOVE__ 146 633
__MOVE__ 164 687
__MOVE__ 475 154
__MOVE__ 518 57
__MOVE__ 651 122
__MOVE__ 873 249

**Comment by retiutut** [comment]
>OpenBCI_GUI::Settings: Creating new GUI-wide Settings file.
>OpenBCI_GUI::Settings: Successfully saved GUI-wide settings to file!

BOOM! 💯

**Comment by retiutut** [comment]
Rolling this fix out to everyone and bumping GUI version to 5.0.8! Standalones will be available soon (aka tonight)!

**Review by retiutut — COMMENTED** [review]
Passing self code review and community testing. Merging to master after bumping version.

**Pull request merged**
