### PR TITLE
wifi shield discovery

### PR DESCRIPTION
**Pull request by Andrey1994**
Signed-off-by: Andrey Parfenov <a1994ndrey@gmail.com>

### CODE REVIEW

**Comment by retiutut** [comment]
Solution to finish the PR:
- Use new `getName()` method to fetch WiFi Serial Number "OpenBCI-XXXX" and save to wifiPortName variable

**Comment by retiutut** [comment]
@Andrey1994 Does this branch have the new version of the GUI helpers w/ `getName()`?

**Comment by Andrey1994** [comment]
Yes

**Comment by retiutut** [comment]
Cool, working on this next.

**Comment by daniellasry** [comment]
What's missing in this PR? no pressure, just wondering.

**Comment by retiutut** [comment]
Screen Shot 2020-04-22 at 10 27 20 AM

**Comment by retiutut** [comment]
In the background, it might be nice to look at the JSON published by the WiFi Shield:
Example: 
http://10.0.1.18/board ->
```
{"board_connected":true,"board_type":"ganglion","num_channels":4,"gains":[51,51,51,51]}
```
When a board is not plugged in correctly, or maybe a power issue, board_connected could be false, and this broadcasts this discrepancy. It's also nice to distinguish the board.

All of this data would be held in the already used Menu list and assists in starting a session.

**Comment by retiutut** [comment]
Screen Shot 2020-04-22 at 10 21 08 PM

**Pull request merged**
