### PR TITLE
Fix brainflow library unpacking for MacOS

### PR DESCRIPTION
**Pull request by philippitts**

### CODE REVIEW

**Comment by philippitts** [comment]
Looks good. Tested both running from Processing 4.3 and running the built DMG on MacOS 12.5.1.

**Comment by philippitts** [comment]
We need to update the documentation to notify developers on MacOS that they will need to set the following environment variable when running from Processing.

```
export ld_library_path=/path/to/libraries/brainflow
```

**Comment by philippitts** [comment]
We also need to update the license agreement popup when installing the application from the DMG on MacOS.

**Comment by retiutut** [comment]
This looks similar to the fix for OpenBCI_GUI_Helpers library!

**Review by retiutut — APPROVED** [review]

**Review by retiutut — CHANGES_REQUESTED** [review]
@philippitts Does this mean we need to copy/paste all dynamic libraries here again when updating brainflow?

**Review by retiutut — APPROVED** [review]

**Pull request merged**
