### PR TITLE
Auto launch hub windows

### PR DESCRIPTION
**Pull request by retiutut**
Address issue #300 

- [x] Update changelog

- [x] Create PR or Issue in the [Docs](https://github.com/OpenBCI/Docs) 

https://github.com/OpenBCI/Docs/pull/159

Steps used to achieve desired result:

Test using Windows 10, Processing 3, and latest OpenBCIHub:
-   Install Hub to correct location http://docs.openbci.com/OpenBCI%20Software/01-OpenBCI_GUI#the-openbci-gui-running-the-openbci-gui-from-the-processing-ide-install-openbci-hub-on-windows
-   Set Hub to Run as Administrator
-   Set Processing, Atom, or Standalone OpenBCI_GUI to Run as Administrator
-   Run sketch or Standalone App

__Code Review Changes:__
- [x] Move Hub to /data/ folder and use dataPath() to access it
https://github.com/OpenBCI/OpenBCI_GUI/pull/420/commits/e696dd89ea7f381f990714b5651a09465a323e02
- [ ] Make PR in Docs (Pictures may need to be changed/removed!) describing placing Hub in /data/ folder for both Standalone and Processing

### CODE REVIEW

**Comment by retiutut** [comment]
@daniellasry This feature/fix is definitely ready. Just needs an update to the docs!

**Comment by retiutut** [comment]
@daniellasry Done.

**Comment by daniellasry** [comment]
When I test this on my machine, it fails to launch:
`hubStart: java.lang.RuntimeException: Exception while attempting C:\Program Files\OpenBCIHub\OpenBCIHub.exe`

It works if I change "exec()" to "launch()". However, the hub does not shut down when I close the GUI. Are you seeing the same thing?

**Comment by daniellasry** [comment]
Nevermind! I forgot to run the GUI as administrator :)

**Comment by daniellasry** [comment]
In Mac and Linux releases, we package the HUB inside the GUI's "data" folder, and launch it from there using a relative path. Why can't we do the same in windows? I tried doing it locally and it seems to work.

Either way, thanks for taking this issue. I'm looking forward to not having to launch the HUB manually!

**Comment by retiutut** [comment]
If you can't see a reason for it to be in /systemDrive/.../Program Files, AND you have tried it, maybe Hub does deserve a new home on Windows!

**Comment by retiutut** [comment]
> It works if I change "exec()" to "launch()". However, the hub does not shut down when I close the GUI. Are you seeing the same thing?

- I did switch to launch() and it works fine with the /data/ folder solution.

- Then I try running the GUI/Hub with Task Manager Open... it looks like the GUI/Hub are under the same Java Process, and both processes close together 💯 👍

**Comment by daniellasry** [comment]
This looks great! Yeah, putting the whole folder under 'data' is the way to go. That's how I tested it.

Just in case, let's ask for @andrewjaykeller 's opinion on this. He might know of some issues we are not aware of.

**Comment by daniellasry** [comment]
I sent him a message. He said he had some driver issues when downloading the release .zip file, but to give it a shot anyway. I've tested your change pretty thoroughly and I'm not seeing any problems. The only thing users need to do is set the GUI to run as admin.

**Comment by daniellasry** [comment]
This fix has been included in v4.0.3-beta.1 windows release. 😎
Thanks!

**Pull request merged**
