### PR TITLE
Added electrodes drag and drop to the head widget

### PR DESCRIPTION
**Pull request by liqwid**
Also added mouseDrag callback to widget class

If electrodes overlap then electrode with a bigger index is in priority for drag.
On dynamic picture colors update occurs after drop of the electrode

There is a small flaw: when data stream is paused and electrode is dragged the static picture won't update with current data.

#138

### CODE REVIEW

**Comment by aj-ptw** [comment]
Thanks looking forward to trying it out!

**Comment by aj-ptw** [comment]
Not working for me when I try to drag? How does this work?

**Comment by liqwid** [comment]
Plain click and hold. Does the border thicken on hover?

Let me check it out at home.

**Comment by aj-ptw** [comment]
problem is in this chunk of code because `isDraggedElecInsideHead` is returning false when I'm for sure inside the head.

```
  private boolean isDraggedElecInsideHead() {
    int dx = mouseX - circ_x;
    int dy = mouseY - circ_y;
    return dx * dx + dy * dy < (circ_diam - elec_diam) / 4;
  }
```

**Comment by liqwid** [comment]
Made a fix in a pull request

**Pull request merged**
