### PR TITLE
Added Cyton and Ganglion wifi

### PR DESCRIPTION
**Pull request by daniellasry**
Currently only works without auto discovery. You need to choose "STATIC IP" and type in the IP of the wifi board.

### CODE REVIEW

**Comment by daniellasry** [comment]
@retiutut or @Andrey1994 could you pull this branch locally and check that Wifi+ganglion is working for you? I think I have a hardware issue on my ganglion board that is preventing wifi shield from working. My board doesn't work in the old gui either.

Cyton wifi works though.

**Comment by retiutut** [comment]
Sure, testing now.

**Comment by daniellasry** [comment]
> I was able to connect to Ganglion+WiFi using static address!
> 
> Here is the console log that I think is showing some cp5 front-end exceptions:
> 
> The Hub exception is from the Control panel WiFi options after pressing ">" button.
> 
> ```
> Console Log Started at Local Time: 2020-03-13_21-44-37
> Screen Resolution: 1920 X 1080
> Welcome to the Processing-based OpenBCI GUI!
> For more information, please visit: https://openbci.github.io/Documentation/docs/06Software/01-OpenBCISoftware/GUIDocs
> Launching application from local data dir
> OpenBCI_GUI: hubStart: OS Detected: Mac
> TopNav: Internet Connection Successful
> Local Version: 420, Latest Version: 420
> GUI is up to date!
> OpenBCI_GUI::Setup: Sample Data exists in Documents folder.
> ControlP5 2.2.6 infos, comments, questions at http://www.sojamo.de/libraries/controlP5
> The file "/Users/Richard/Documents/OpenBCI_GUI/Settings/UserPlaybackHistory.json" is missing or inaccessible, make sure the URL is valid or that the file has been added to your sketch and is readable.
> OpenBCI_GUI::Control Panel: Playback history file not found or other error.
> OpenBCI_GUI::Setup: Setup is complete!
> sourceList: click! 
> channel count set to 4
> Setting Latency to 10000
> Setting WiFi Internet Protocol to tcp
> Setting WiFi style to dynamic
> protocolWifiGanglion
> Setting WiFi style to static
> [INFO]: Using Static IP address of the WiFi Shield!
> CP: WiFi IP: Using Static IP address of the WiFi Shield!
> Static IP address of 10.0.1.27
> [DEFAULT]: Static IP address of 10.0.1.27
> java.lang.Exception
> 	at OpenBCI_GUI$Hub.write(OpenBCI_GUI.java:12739)
> 	at OpenBCI_GUI$Hub.writeJSON(OpenBCI_GUI.java:11890)
> 	at OpenBCI_GUI$Hub.examineWifi(OpenBCI_GUI.java:12612)
> 	at OpenBCI_GUI$ControlPanel.CPmouseReleased(OpenBCI_GUI.java:4733)
> 	at OpenBCI_GUI.mouseReleased(OpenBCI_GUI.java:11052)
> 	at processing.core.PApplet.mouseReleased(PApplet.java:2810)
> 	at processing.core.PApplet.handleMouseEvent(PApplet.java:2719)
> 	at processing.core.PApplet.dequeueEvents(PApplet.java:2613)
> 	at processing.core.PApplet.handleDraw(PApplet.java:2454)
> 	at processing.opengl.PSurfaceJOGL$DrawListener.display(PSurfaceJOGL.java:886)
> 	at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:692)
> 	at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:674)
> 	at jogamp.opengl.GLAutoDrawableBase$2.run(GLAutoDrawableBase.java:443)
> 	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1293)
> 	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147)
> 	at com.jogamp.newt.opengl.GLWindow.display(GLWindow.java:768)
> 	at com.jogamp.opengl.util.AWTAnimatorImpl.display(AWTAnimatorImpl.java:81)
> 	at com.jogamp.opengl.util.AnimatorBase.display(AnimatorBase.java:453)
> 	at com.jogamp.opengl.util.FPSAnimator$MainTask.run(FPSAnimator.java:178)
> 	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
> 	at java.base/java.util.TimerThread.run(Timer.java:506)
> Hub: killAndShowMsg: Hub has crashed, please restart your application.
> Error: Attempted to TCP write with no server connection initialized
> Settings: LogFileMaxDuration = 60 minutes
> Static IP address of 10.0.1.27
> [DEFAULT]: Attempting to Start Session...
> initButtonPressed: Calling initSystem() after next draw()
> OpenBCI_GUI: Start session. Calling initSystem().
> 
> 
> =================================================
> ||             INITIALIZING SYSTEM             ||
> =================================================
> 
> channel count set to 4
> Networking Data Types || show num dropdowns = 6
> headPlot: computeWeightFactor: Ielec 0, solution complete with 2000 iterations. max_dVal = 1.0759383E-5
> headPlot: computeWeightFactor: Ielec 1, solution complete with 2000 iterations. max_dVal = 1.0493398E-5
> headPlot: computeWeightFactor: Ielec 2, solution complete with 2000 iterations. max_dVal = 8.711815E-5
> headPlot: computeWeightFactor: Ielec 3, solution complete with 2000 iterations. max_dVal = 8.860826E-5
> InitSettings: Saving Default Settings to file!
> SoftwareSettings: 4 active widgets saved!
> InitSettings: /Users/Richard/Documents/OpenBCI_GUI/Settings/GanglionUserSettings.json not found or other error.
> SoftwareSettings: Removed old/broken settings file.
> [DEFAULT]: The new data source is LIVE (from Ganglion) and NCHAN = [4]. User Settings Error: Default Settings Loaded.
> [DEFAULT]: Data stream started.
> Brainflow start streaming
> OpenBCI_GUI: openNewLogFile: opened ODF output file: /Users/Richard/Documents/OpenBCI_GUI/Recordings/OpenBCISession_2020-03-13_21-44-45/OpenBCI-RAW-2020-03-13_21-50-24.txt
> java.lang.reflect.InvocationTargetException
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
> 	at controlP5.ControlBroadcaster.invokeMethod(Unknown Source)
> 	at controlP5.ControlBroadcaster.callTarget(Unknown Source)
> 	at controlP5.ControlBroadcaster.broadcast(Unknown Source)
> 	at controlP5.Controller.broadcast(Unknown Source)
> 	at controlP5.Controller.setValue(Unknown Source)
> 	at controlP5.ScrollableList.updateIndex(Unknown Source)
> 	at controlP5.ScrollableList.onRelease(Unknown Source)
> 	at controlP5.Controller.setMousePressed(Unknown Source)
> 	at controlP5.ControllerGroup.setMousePressed(Unknown Source)
> 	at controlP5.ControlWindow.mouseReleasedEvent(Unknown Source)
> 	at controlP5.ControlWindow.mouseEvent(Unknown Source)
> 	at jdk.internal.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
> 	at processing.core.PApplet$RegisteredMethods.handle(PApplet.java:1397)
> 	at processing.core.PApplet.handleMethods(PApplet.java:1599)
> 	at processing.core.PApplet.handleMouseEvent(PApplet.java:2710)
> 	at processing.core.PApplet.dequeueEvents(PApplet.java:2613)
> 	at processing.core.PApplet.handleDraw(PApplet.java:2454)
> 	at processing.opengl.PSurfaceJOGL$DrawListener.display(PSurfaceJOGL.java:886)
> 	at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:692)
> 	at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:674)
> 	at jogamp.opengl.GLAutoDrawableBase$2.run(GLAutoDrawableBase.java:443)
> 	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1293)
> 	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147)
> 	at com.jogamp.newt.opengl.GLWindow.display(GLWindow.java:768)
> 	at com.jogamp.opengl.util.AWTAnimatorImpl.display(AWTAnimatorImpl.java:81)
> 	at com.jogamp.opengl.util.AnimatorBase.display(AnimatorBase.java:453)
> 	at com.jogamp.opengl.util.FPSAnimator$MainTask.run(FPSAnimator.java:178)
> 	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
> 	at java.base/java.util.TimerThread.run(Timer.java:506)
> Caused by: java.lang.NullPointerException
> 	at OpenBCI_GUI.Duration(OpenBCI_GUI.java:27492)
> 	... 35 more
> [DEFAULT]: Data stream stopped.
> Brainflow stop streaming
> java.lang.reflect.InvocationTargetException
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
> 	at controlP5.ControlBroadcaster.invokeMethod(Unknown Source)
> 	at controlP5.ControlBroadcaster.callTarget(Unknown Source)
> 	at controlP5.ControlBroadcaster.broadcast(Unknown Source)
> 	at controlP5.Controller.broadcast(Unknown Source)
> 	at controlP5.Controller.setValue(Unknown Source)
> 	at controlP5.ScrollableList.updateIndex(Unknown Source)
> 	at controlP5.ScrollableList.onRelease(Unknown Source)
> 	at controlP5.Controller.setMousePressed(Unknown Source)
> 	at controlP5.ControllerGroup.setMousePressed(Unknown Source)
> 	at controlP5.ControlWindow.mouseReleasedEvent(Unknown Source)
> 	at controlP5.ControlWindow.mouseEvent(Unknown Source)
> 	at jdk.internal.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
> 	at processing.core.PApplet$RegisteredMethods.handle(PApplet.java:1397)
> 	at processing.core.PApplet.handleMethods(PApplet.java:1599)
> 	at processing.core.PApplet.handleMouseEvent(PApplet.java:2710)
> 	at processing.core.PApplet.dequeueEvents(PApplet.java:2613)
> 	at processing.core.PApplet.handleDraw(PApplet.java:2454)
> 	at processing.opengl.PSurfaceJOGL$DrawListener.display(PSurfaceJOGL.java:886)
> 	at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:692)
> 	at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:674)
> 	at jogamp.opengl.GLAutoDrawableBase$2.run(GLAutoDrawableBase.java:443)
> 	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1293)
> 	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147)
> 	at com.jogamp.newt.opengl.GLWindow.display(GLWindow.java:768)
> 	at com.jogamp.opengl.util.AWTAnimatorImpl.display(AWTAnimatorImpl.java:81)
> 	at com.jogamp.opengl.util.AnimatorBase.display(AnimatorBase.java:453)
> 	at com.jogamp.opengl.util.FPSAnimator$MainTask.run(FPSAnimator.java:178)
> 	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
> 	at java.base/java.util.TimerThread.run(Timer.java:506)
> Caused by: java.lang.NullPointerException
> 	at OpenBCI_GUI.Duration(OpenBCI_GUI.java:27492)
> 	... 35 more
> [DEFAULT]: Data stream started.
> Brainflow start streaming
> OpenBCI_GUI: openNewLogFile: opened ODF output file: /Users/Richard/Documents/OpenBCI_GUI/Recordings/OpenBCISession_2020-03-13_21-44-45/OpenBCI-RAW-2020-03-13_21-53-16.txt
> ConsoleLog: Copying console log to clipboard!
> ConsoleLog: Opening console log as text file!
> ConsoleLog: Console closed!
> ConsoleLog: Copying console log to clipboard!
> ```

Thanks, i'll try to fix these

**Comment by daniellasry** [comment]
Fixed the HUB issue. Not sure what's causing the InvocationTargetException, I may need a local repro to be able to fix it.

**Pull request merged**
