### PR TITLE
stop streaming for hardware settings

### PR DESCRIPTION
**Pull request by Andrey1994**
Signed-off-by: Andrey Parfenov <a1994ndrey@gmail.com>

### CODE REVIEW

**Comment by Andrey1994** [comment]
> The "Stop Data Stream" button needs to change text and color to ~ "Start Data Stream". I can look at this later.
> 
> aka front-end stuff.

I think its not required, mostly because as soon as you close hardware settings window streaming will be restarted automatically, so you dont need to click at this button

**Comment by retiutut** [comment]
That's a break in data, and it affects playback files also! I really need to look at this first before merging.

**Comment by retiutut** [comment]
It needs to hard stop the data stream, and cause users to click "Start Data Stream".

**Comment by Andrey1994** [comment]
Users dont need to click start stream because stream will be started as soon as settings are closed

**Comment by retiutut** [comment]
Solution for Later: 
- Auto-restart stream like Andrey suggests
- Grey out and disable "Start Stream button" while hardware settings controller is open

**Comment by Andrey1994** [comment]
there is one more option, if streaming is running and somebody clicks on hardware setting button instead openning settings widget create a message like 'you need to stop streaming before changing settings'

**Pull request closed without merging**
